# 使用 nginx 作为前端容器
FROM nginx:alpine

# 删除默认网页
RUN rm -rf /usr/share/nginx/html/*

# 拷贝前端文件到 nginx html 目录
COPY ./dist/ /usr/share/nginx/html/

# 拷贝自定义 Nginx 配置
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
